@startuml
left to right direction

actor Client
actor Admin

rectangle "gestionFactures API" {
  usecase "S'inscrire / Se connecter" as auth
  usecase "Voir son profil" as me
  usecase "Gérer fournisseurs (CRUD)" as suppliers
  usecase "Gérer factures (CRUD)" as invoices
  usecase "Enregistrer un paiement" as payment
  usecase "Voir les paiements" as getPayments

  usecase "Lister tous les clients" as adminClients
  usecase "Voir données d'un client" as adminData
}

Client --> auth
Client --> me
Client --> suppliers
Client --> invoices
Client --> payment
Client --> getPayments

Admin --> auth
Admin --> adminClients
Admin --> adminData
@enduml
